// Generated by ts-to-zod
import { z } from "zod";

export const articleConvertBodySchema = z.object({
  mode: z.union([z.literal("render"), z.literal("revert")]),
});

export const articleConvertReqSchema = z.object({
  articleId: z.string(),
});

export const articleConvertResSchema = z.object({
  changed: z.boolean(),
  count: z.number(),
  disabled: z.boolean(),
  error: z.string().optional(),
});

export const issueConvertBodySchema = z.object({
  mode: z.union([z.literal("render"), z.literal("revert")]),
});

export const issueConvertReqSchema = z.object({
  issueId: z.string(),
});

export const issueConvertResSchema = z.object({
  changed: z.boolean(),
  count: z.number(),
  disabled: z.boolean(),
  error: z.string().optional(),
});

export const projectTypesGETReqSchema = z.object({
  projectId: z.string(),
});

export const projectTypesGETResSchema = z.object({
  autoConvert: z.boolean(),
  types: z.array(
    z.object({
      key: z.string(),
      title: z.string(),
      accent: z.string(),
      background: z.string(),
      icon: z.string(),
      enabled: z.boolean(),
    }),
  ),
});

export const projectTypesPOSTBodySchema = z.object({
  autoConvert: z.boolean(),
  types: z.array(
    z.object({
      key: z.string(),
      title: z.string(),
      accent: z.string(),
      background: z.string(),
      icon: z.string(),
      enabled: z.boolean(),
    }),
  ),
});

export const projectTypesPOSTReqSchema = z.object({
  projectId: z.string(),
});

export const projectTypesPOSTResSchema = z.object({
  saved: z.boolean(),
  error: z.string().optional(),
});

// Nested schema object for validation system
export const schema = {
  article: {
    convert: {
      POST: {
        Req: articleConvertReqSchema,
        Res: articleConvertResSchema
      }
    }
  },
  issue: {
    convert: {
      POST: {
        Req: issueConvertReqSchema,
        Res: issueConvertResSchema
      }
    }
  },
  project: {
    types: {
      GET: {
        Req: projectTypesGETReqSchema,
        Res: projectTypesGETResSchema
      },
      POST: {
        Req: projectTypesPOSTReqSchema,
        Res: projectTypesPOSTResSchema
      }
    }
  }
};
